### ISSUE TITLE
FIO history: not all TXs are returned

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/blockatlas#1000]
curl `https://blockatlas.trustwallet.com/v1/fio/FIO6XKiobBGrmPZDaHne47TF25CamjFc3cRe8hs7oAiCN59TbJzes`

```json
{
	"total": 1,
	"docs": [{
		"id": "7fe6bfdc3e536ce2fec7623273b68b9e496f04c12d0e9426ab6d5a0a59c06467",
		"coin": 235,
		"from": "rpxtnpsr3gxd",
		"to": "fio.treasury",
		"fee": "0",
		"date": 1585871869,
		"block": 1553003,
		"status": "completed",
		"type": "transfer",
		"direction": "outgoing",
		"memo": "FIO API fees. Thank you.",
		"metadata": {
			"value": "2000000000",
			"symbol": "FIO",
			"decimals": 9
		}
	}],
	"status": true
}
```

The correct value is 5 FIO, fee is 2 FIO :
https://explorer.fioprotocol.io/transaction/7fe6bfdc3e536ce2fec7623273b68b9e496f04c12d0e9426ab6d5a0a59c06467

**Comment by hewigovens** [comment]
technically speaking, it's not wrong, transfer to public key has a few actions, this one is transfering to `fio.treasury` for fee

**Comment by catenocrypt** [comment]
This transaction shows up the same way in the FIO explorer as well:
https://explorer.fioprotocol.io/account/rpxtnpsr3gxd

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/13562139/78344625-f260ce80-759c-11ea-84b3-b2dcdd358792.png">

The real problem is, why are the other transactions not shown, only the first one?

API call to FIO history API returns only 4 actions, and only the first transaction is among these.  There are many more actions, so the question is why we get only the first 4 actions.

```
curl -H "Content-Type: application/json" -d '{"account_name": "rpxtnpsr3gxd"}' https://fio.eosphere.io/v1/history/get_actions
```

**Comment by hewigovens** [comment]
can you try https://fio.greymass.com/? I can get 9 actions

**Comment by catenocrypt** [comment]
Unfortunately including pos/offset parameters does not help either.  Less offset returns less, but more than 4 still returns 4.
```
curl -H "Content-Type: application/json" -d '{"account_name": "rpxtnpsr3gxd", "pos": -1, "offset": -20}' https://fio.eosphere.io/v1/history/get_actions
```

**Comment by catenocrypt** [comment]
Issues and solutions:
- Not all transfers are returned: include offset: -100 in query
- Not all transfers are returned: include offset: Switch to fio.greymass.com API
- The "trnsfiopubky" actions don't show up as transfers: handle them as well.
