### ISSUE TITLE
Blockatlas not returning Cosmos transaction

### ISSUE THREAD

**Issue by wpank** [TrustWallet/blockatlas#179]
[The following transaction](https://www.mintscan.io/txs/5FE39224EF089BCCFE279A1202251A1705A05BA9663B825CBA3EECF570F7C1FE) does not [show up in a blockatlas request for that address](/v1/cosmos/cosmos135qla4294zxarqhhgxsx0sw56yssa3z0f78pm0). 

Parameters of transaction: 
```
{
      tx: {
        fee: {amount: [{amount: '200', denom: 'uatom'}], gas: '200000'},
        memo: '',
        msg: [
          {
            type: 'cosmos-sdk/MsgSend',
            value: {
              amount: [{amount: '1', denom: 'uatom'}],
              from_address: 'cosmos1hsk6jryyqjfhp5dhc55tc9jtckygx0eph6dd02',
              to_address: 'cosmos135qla4294zxarqhhgxsx0sw56yssa3z0f78pm0',
            },
          },
        ],
        signatures: [
          {
            pub_key: {
              type: 'tendermint/PubKeySecp256k1',
              value: 'AlcobsPzfTNVe7uqAAsndErJAjqplnyudaGB0f+R+p3F',
            },
            signature:
              'Pdc+859ZRLogUtb5KqAAJHwtpEc2jZBCBkhdOZGimsRlZeuO4UC7AaIGbwaaQ4yw01L4Jiy2SRuVTcVnUPTL6g==',
          },
        ],
        type: 'cosmos-sdk/MsgSend',
      },
      mode: 'sync',
    }
```

yeilds the following transaction hash:

`5FE39224EF089BCCFE279A1202251A1705A05BA9663B825CBA3EECF570F7C1FE`

**Comment by wpank** [comment]
[Another transaction](https://hubble.figment.network/cosmos/chains/cosmoshub-2/blocks/1122180/transactions/EB62030162AAC1AA347E87F440CF5604EA70FB9EB3584C9EEEB618DA3920E4CD?format=json)

**Comment by jamesscaur** [comment]
Thanks @wpank.

It seems that everything post `3B65E82A6E985DDA47F1CDE244FB1A944915BB9B9D83EC37CC2AE1D7A10A17CC` (e.g. [this](https://www.mintscan.io/txs/49328879b1a8b16fe06b8fba8b01de7b2b8759de66dff8844e87698e82d82b42), [this](https://www.mintscan.io/txs/9ae4b4fa02108d14cf921e36b4cf6a6ca254073ab0076813803649dbdd7559bd), or [this](https://www.mintscan.io/txs/d6493a9b061bcbea3148fbf50cebcfa20a03206c8ddbd0f594c0fed4e5d913e6)) isn't showing up.

Perhaps a sync issue past block ~803000 ([seemingly regaining it for recent blocks](https://www.mintscan.io/txs/d6493a9b061bcbea3148fbf50cebcfa20a03206c8ddbd0f594c0fed4e5d913e6)) or a change in the way transactions are broadcasted?

Will look into it.

**Comment by jamesscaur** [comment]
Haven't had a chance to get to this today, have scheduled some time tomorrow.

**Comment by jamesscaur** [comment]
Seems to be an issue with using the tags sender/reciever on http://stargate.cosmos.network/ - ill see if theres any other valid way of finding transfers.

https://cosmos.network/rpc/#/ICS0/get_txs

**Comment by jamesscaur** [comment]
Found the issue!

Searching [by sender](https://stargate.cosmos.network/txs?sender=cosmos1hsk6jryyqjfhp5dhc55tc9jtckygx0eph6dd02) and [reciever](https://stargate.cosmos.network/txs?recipient=cosmos135qla4294zxarqhhgxsx0sw56yssa3z0f78pm0) on Stargate will both list ```5FE39224EF089BCCFE279A1202251A1705A05BA9663B825CBA3EECF570F7C1FE``` in their results. At array level 1 and 30 respectively.

Therefore, a request for either with a limit of 25 (Blockatlas standard) will only result in ```5FE39224EF089BCCFE279A1202251A1705A05BA9663B825CBA3EECF570F7C1FE``` being visible for a Blockatlas query for ```cosmos1hsk6jryyqjfhp5dhc55tc9jtckygx0eph6dd02``` - [which can be verified here.](http://blockatlas.trustwalletapp.com/v1/cosmos/cosmos1hsk6jryyqjfhp5dhc55tc9jtckygx0eph6dd02)

I double checked the tags for sender/receiver, and verified that [Blockatlas does see both sent/received transactions](http://blockatlas.trustwalletapp.com/v1/cosmos/cosmos16v3f95amtvpewuajjcdsvaekuuy4yyzuyynp4t) (search for ```ec55a2a4927dd6e323b65ae0bb109b9343d261a49fa0689172fe52f6371bff21```).

I also checked that Blockatlas is getting both the sent and received transactions in order, and not neglecting one over the other. (i.e. my theory was that because Stargate does not allow one to see both sent and received transactions at once, what was happening is that the 25-transaction limit is being reached first with "sent" transactions and there is no room for more recent "received" transactions.)

But that isn't the case, since [a request for this address actually returns a total of 50, not 25.](http://blockatlas.trustwalletapp.com/v1/cosmos/cosmos135qla4294zxarqhhgxsx0sw56yssa3z0f78pm0) In fact if Cosmos was consistent with other Blockatlas platforms it would remove the 25 least recent transactions before returning the response.

So that's why you can't see ```5FE39224EF089BCCFE279A1202251A1705A05BA9663B825CBA3EECF570F7C1FE``` on a request for ```cosmos135qla4294zxarqhhgxsx0sw56yssa3z0f78pm0```. It's above the 25 (actually 50) transaction limit.

@vikmeup what do you think is the best solution to this? Increase the transaction limit?
