### ISSUE TITLE
[Tezos] value not returned

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/blockatlas#39]
http://blockatlas-trust.herokuapp.com/v1/tezos/tz1WDujRWCYjLBDfZieXW6insg5EUbg1rCRK

```
metadata: {
   value: ""
}
``` 

value is empty

**Comment by terorie** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/21371810/55289758-0cd0fc80-53cb-11e9-8ba9-f0ad5a30d469.png">
Turns out tzscan.io isn't consistent on data types. Some other APIs probably have this problem too.

I'll introduce an `Amount` data type that unmarshals both strings and numbers into a string holding a decimal number instead.

**Comment by vikmeup** [comment]
That’s very typical for tezos - inconsistency!
