### ISSUE TITLE
[Market] Pricing not shown for token

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#685]
## Summary of Bug

Not specific 

https://coinmarketcap.com/currencies/xio/ (Price not available)
https://www.coingecko.com/en/coins/xio (Price available)

Currently price not being returned for this token. but it should because CG has price for it

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Pantani** [comment]
@vikmeup can you give me more info? What of these tokens you are meaning?

Official XIO ERC20, the price works:
![Image from iOS](https://user-images.githubusercontent.com/2406457/73097879-fbf7f700-3ec6-11ea-8763-a87aca28d4c4.png)

BOMBX XIO ERC20 doesn't have a price:
![Image from iOS (1)](https://user-images.githubusercontent.com/2406457/73097889-01554180-3ec7-11ea-8c88-9f8e3cf92b54.png)

XIO BEP 2 doesn't have a price, make sense because the coin is 714 and the price doesn't exist inside the dex:
![Image from iOS (2)](https://user-images.githubusercontent.com/2406457/73097900-04503200-3ec7-11ea-9d47-57c00fd8e38f.png)


```
curl -X POST \
  https://<BLOCKATLAS>/v1/market/ticker \
  -d '{
  "currency": "USD",
  "assets": [
    {
      "coin": 60, 
      "type": "token",
      "token_id": "0x0f7F961648aE6Db43C75663aC7E5414Eb79b5704"
    }
  ]
}'
```

```
{
   "currency" : "USD",
   "docs" : [
      {
         "coin" : 60,
         "last_update" : "2020-01-24T19:09:58.683Z",
         "price" : {
            "change_24h" : 4.72287,
            "value" : 0.00875329
         },
         "token_id" : "0x0f7f961648ae6db43c75663ac7e5414eb79b5704",
         "type" : "token"
      }
   ]
}
```

**Comment by Pantani** [comment]
I can't simulate this behavior
