### ISSUE TITLE
[Platform] Define Error Response

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/blockatlas#836]
## Summary of Bug

Currently error response type has duplicated data and not intuitive to use

```
{
   "code":500,
   "error":{
      "error":"Validator not found: Unable to fetch delegations list",
      "meta":{
         "Balance":"5383274",
         "Delegate":"tz1egbN6RK2bM5vt4aAZw6r9j4nL8z49bPdS"
      }
   }
}
```

## Expected Behavior

TODO: Define

**Comment by arein** [comment]
What does "Validator not found" mean - should this also be a HTTP 404 error code?
The summary hints at this being a HTTP 500 status

**Comment by vikmeup** [comment]
Yes, there is two problems: 

1) wrong status code 
2) error response is not well designed, there is an error value inside an error object

**Comment by EnoRage** [comment]
Let's design a new version of handlers for Platform REST API? I recommend reading that before
https://github.com/microsoft/api-guidelines
https://medium.com/@schneidenbach/restful-api-best-practices-and-common-pitfalls-7a83ba3763b5

**Comment by arein** [comment]
+1

**Comment by vikmeup** [comment]
```
{
    "error": {
        "code": 409,
        "message": "Link alias conflict"
    }
}
```

```
{
    "error": {
        "code": 400,
        "message": "Some error"
    }
}
```

Best format for errors.

**Comment by thomasxnguy** [comment]
Some remarks :

- Errors are managed within the router logic, it might be good to consider using a handler so that all the logic regarding the api error response can be gathered into one place
Some code about how to use the gin middleware
https://stackoverflow.com/questions/48224908/better-error-handling  

- Putting the `HTTP code` as `code` seems a bit redundant since this information can be directly retrieved from the response object.
Maybe it would be good to defined "application specific error code" which can be a number code "0001", a string code "A0001" etc.. That would help to make things easier for the consumer of the api so that he can implement his logics accordingly the error code (better than parsing a string)>

An example of list of `error code`

https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by terorie** [comment]
I recommend RFC 7807: "Problem Details for HTTP APIs".
Simple and widely used.
https://tools.ietf.org/html/rfc7807#section-3

**Comment by EnoRage** [comment]
#1015
